name: 每日构建

on:
  schedule:
    - cron:  '0 0 * * *'  # 每天凌晨 00:00 UTC 触发
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 检出ESurfingDialer代码
      uses: actions/checkout@v4
      with:
        repository: 'Rsplwe/ESurfingDialer'
        path: './ESurfingDialer'

    - name: 设置 JDK 20
      uses: actions/setup-java@v4
      with:
        java-version: '20'
        distribution: 'zulu'

    - name: 进入ESurfingDialer目录并执行构建
      run: |
        cd ./ESurfingDialer
        ./gradlew shadowJar

    - name: 编译ESurfingDockerPhone镜像
      run: |
        cd Phone
        chmod +x ./build.sh
        ./build.sh

    - name: 获取天翼校园网官方Linux版本下载地址并下载
      run: |
        cd ./PC/
        pip3 install requests beautifulsoup4 lxml
        python3 ./Get_ESurfingDialerClient.py

    - name: 创建发布并上传构建产物
      uses: softprops/action-gh-release@v2
      with:
        tag_name: V$(date +"%Y.%m.%d.%H.%M.%S.%N")
        name: ESurfingDialer Release $(date +"%Y.%m.%d.%H.%M.%S.%N")
        draft: false
        prerelease: false
        files: |
          ./ESurfingDialer/build/libs/*.jar
          ./Phone/ESurfingDockerPhone.tar.gz
          ./Phone/ESurfingDialer.zip
        fail_on_unmatched_files: true
