name: 每日构建

on:
  schedule:
    - cron:  '0 0 * * *'  # 每天凌晨 00:00 UTC 触发
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest  # 在最新的 Ubuntu 环境中运行

    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      with:
        repository: 'Rsplwe/ESurfingDialer'  # 指定需要检出的公开仓库

    - name: 设置 JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'zulu'

    - name: 进入 gradlew 文件所在的目录并执行构建
      run: |
        cd ./ESurfingDialer  # 替换为你的 gradlew 文件所在的目录
        ./gradlew shadowJar  # 执行 Gradle 构建脚本

    - name: 上传构建产物
      uses: actions/upload-artifact@v3
      with:
        name: shadowJar
        path: ./ESurfingDialer/build/*  # 替换为你的构建产物路径
