name: 每日构建

on:
  schedule:
    - cron:  '0 8 * * *'  # 东八区每天凌晨 00:00 UTC+8 触发
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write
  discussions: write

jobs:
  build:
    runs-on: ubuntu-latest  # 在最新的 Ubuntu 环境中运行

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 检出ESurfingDialer代码
      uses: actions/checkout@v4
      with:
        repository: 'Rsplwe/ESurfingDialer'
        path: './ESurfingDialer'

    - name: 设置 JDK 20
      uses: actions/setup-java@v4
      with:
        java-version: '20'
        distribution: 'zulu'

    - name: 查看当前目录下点文件
      run: |
        ls -l

    - name: 进入ESurfingDialer目录并执行构建
      run: |
        cd ./ESurfingDialer
        ./gradlew shadowJar

    - name: 上传ESurfingDialer的JAR构建产物
      uses: actions/upload-artifact@v3
      with:
        name: ESurfingDialer的JAR构建产物
        path: './ESurfingDialer/build/libs/*'

    - name: 编译OracleJava镜像
      run: |
        chmod +x ./OracleJava.sh
        ./OracleJava.sh

    - name: 编译ESurfingDockerPhone镜像
      run: |
        cd Phone
        chmod +x ./build.sh
        ./build.sh

    - name: 上传ESurfingDockerPhone的Docker镜像
      uses: actions/upload-artifact@v3
      with:
        name: ESurfingDockerPhone的Docker镜像
        path: './Phone/ESurfingDockerPhone.tar.gz'

    - name: 下载Java21
      run: |
        chmod +x ./Phone/Download_jdk21.sh
        cd ./Phone/
        ./Download_jdk21.sh

    - name: 修改Phone下的Direct文件夹为ESurfingDialer
      run: |
        cd ./Phone/
        mv ./Direct ./ESurfingDialer

    - name: 上传ESurfingDialer的免Docke直接运行版本
      uses: actions/upload-artifact@v3
      with:
        name: ESurfingDialer的免Docke直接运行版本
        path: './Phone/ESurfingDialer/'

    - name: 生成更新日志
      id: generate_changelog
      run: |
        echo "更新日志：" > ${{ github.workspace }}-CHANGELOG.txt
        echo "" >> ${{ github.workspace }}-CHANGELOG.txt
        echo "以下是本次构建的各个产物及其说明：" >> ${{ github.workspace }}-CHANGELOG.txt
        echo "" >> ${{ github.workspace }}-CHANGELOG.txt
        echo "ESurfingDialer的JAR构建产物:" >> ${{ github.workspace }}-CHANGELOG.txt
        find ./ESurfingDialer/build/libs/ -name '*-all.jar' -exec echo "- {}" \; >> ${{ github.workspace }}-CHANGELOG.txt
        echo "" >> ${{ github.workspace }}-CHANGELOG.txt
        echo "ESurfingDockerPhone的Docker镜像:" >> ${{ github.workspace }}-CHANGELOG.txt
        echo "- Phone/ESurfingDockerPhone.tar.gz" >> ${{ github.workspace }}-CHANGELOG.txt
        echo "" >> ${{ github.workspace }}-CHANGELOG.txt
        echo "ESurfingDialer的免Docke直接运行版本:" >> ${{ github.workspace }}-CHANGELOG.txt
        echo "- Phone/ESurfingDialer/" >> ${{ github.workspace }}-CHANGELOG.txt

    - name: 创建Release
      uses: softprops/action-gh-release@v2
      with:
        body_path: ${{ github.workspace }}-CHANGELOG.txt
        tag_name: ${{ github.sha }}
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          ./ESurfingDialer/build/libs/* # ESurfingDialer的JAR构建产物
          ./Phone/ESurfingDockerPhone.tar.gz # ESurfingDockerPhone的Docker镜像
          ./Phone/ESurfingDialer/* # ESurfingDialer的免Docke直接运行版本
