name: 每日构建

on:
  schedule:
    - cron:  '0 0 * * *'  # 每天凌晨 00:00 UTC 触发
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest  # 在最新的 Ubuntu 环境中运行

    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 检出ESurfingDialer代码
      uses: actions/checkout@v3
      with:
        repository: 'Rsplwe/ESurfingDialer'
        path: './ESurfingDialer'

    - name: 设置 JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'zulu'

    - name: 查看当前目录下点文件
      run: |
        ls -l

    - name: 进入ESurfingDialer目录并执行构建
      run: |
        cd ./ESurfingDialer
        ./gradlew shadowJar

    - name: 上传构建产物
      uses: actions/upload-artifact@v3
      with:
        name: ESurfingDialer的最新编译JAR（占用手机上网名额）
        path: './ESurfingDialer/build/libs/*'

    - name: 查找最新构建的Jar文件并复制
      run: |
        chmod +x ./FindLasterBuildJar.sh
        ./FindLasterBuildJar.sh

    - name: 检出Oracle-Docker-images代码
      uses: actions/checkout@v3
      with:
        repository: 'oracle/docker-images'
        path: './Oracle-Docker-images'

#    - name: 安装Docker
#      run: |
#        sudo apt update   #没有sudo缺少权限
#        sudo apt install -y docker.io   #没有sudo缺少权限

    - name: 编译OracleJava镜像
      run: |
        chmod +x ./OracleJava.sh
        ./OracleJava.sh


    - name: 编译ESurfingDockerPhone镜像
      run: |
        cd Phone
        chmod +x ./build.sh
        ./build.sh

    - name: 上传构建产物
      uses: actions/upload-artifact@v3
      with:
        name: ESurfingDocker的Docker镜像（占用手机上网名额）
        path: './Phone/ESurfingDockerPhone.tar.gz'

    - name: 下载Java21
      run: |
        chmod +x ./Phone/Download_jdk21.sh
        cd ./Phone/
        ./Download_jdk21.sh

    - name: 查看PC目录下点文件
      run: |
        cd ./Phone/
        ls -l ./Direct/jdk-21_windows-x64
        ls -l ./Direct/jdk-21_linux-x64

    - name: 获取天翼校园网官方Linux版本下载地址并下载，不能获取则使用预下载文件
      run: |
        cd ./PC/
        pip3 install requests beautifulsoup4 lxml
        python3 ./Get_ESurfingDialerClient.py

#    - name: 解压天翼校园网官网Linux客户端V2.4.03.23101901
#      run: |
#        cd ./PC/
#        tar -zxvf ESurfingDialerClient.tar.gz -C .

    - name: 查看PC目录下点文件
      run: |
        ls -l ./PC/
