name: 每日构建

on:
  schedule:
    - cron:  '0 8 * * *'  # 东八区每天凌晨 00:00 UTC+8 触发
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write
  discussions: write

jobs:
  build:
    runs-on: ubuntu-latest  # 在最新的 Ubuntu 环境中运行

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 检查当前目录
      run: |
        ls -l

    - name: 检出ESurfingDialer代码
      uses: actions/checkout@v4
      with:
        repository: 'Rsplwe/ESurfingDialer'
        path: './ESurfingDialer'

    - name: 检查ESurfingDialer目录
      run: |
        ls -l ./ESurfingDialer

    - name: 设置 JDK 20
      uses: actions/setup-java@v4
      with:
        java-version: '20'
        distribution: 'zulu'

    - name: 检查JDK设置
      run: |
        java -version

    - name: 进入ESurfingDialer目录并执行构建
      run: |
        cd ./ESurfingDialer
        ./gradlew shadowJar

    - name: 检查ESurfingDialer构建产物
      run: |
        ls -l ./ESurfingDialer/build/libs

    - name: 上传ESurfingDialer的JAR构建产物
      uses: actions/upload-artifact@v3
      with:
        name: ESurfingDialer的JAR构建产物
        path: './ESurfingDialer/build/libs/*'

    - name: 查找最新构建的Jar文件并复制
      run: |
        chmod +x ./FindLasterBuildJar.sh
        ./FindLasterBuildJar.sh

    - name: 检查Jar文件复制结果
      run: |
        ls -l

    - name: 检出Oracle-Docker-images代码
      uses: actions/checkout@v4
      with:
        repository: 'oracle/docker-images'
        path: './Oracle-Docker-images'

    - name: 检查Oracle-Docker-images目录
      run: |
        ls -l ./Oracle-Docker-images

    - name: 编译OracleJava镜像
      run: |
        chmod +x ./OracleJava.sh
        ./OracleJava.sh

    - name: 检查OracleJava镜像编译结果
      run: |
        ls -l

    - name: 编译ESurfingDockerPhone镜像
      run: |
        cd Phone
        chmod +x ./build.sh
        ./build.sh

    - name: 检查ESurfingDockerPhone镜像编译结果
      run: |
        ls -l ./Phone

    - name: 上传ESurfingDockerPhone的Docker镜像
      uses: actions/upload-artifact@v3
      with:
        name: ESurfingDockerPhone的Docker镜像
        path: './Phone/ESurfingDockerPhone.tar.gz'

    - name: 下载Java21
      run: |
        chmod +x ./Phone/Download_jdk21.sh
        cd ./Phone/
        ./Download_jdk21.sh

    - name: 检查Java21下载结果
      run: |
        ls -l ./Phone/Direct

    - name: 修改Phone下的Direct文件夹为ESurfingDialer
      run: |
        cd ./Phone/
        mv ./Direct ./ESurfingDialer

    - name: 检查修改后的文件夹
      run: |
        ls -l ./Phone/ESurfingDialer

    - name: 压缩ESurfingDialer文件夹为zip格式
      run: |
        cd ./Phone/
        zip -r ESurfingDialer.zip ESurfingDialer

    - name: 检查压缩文件
      run: |
        ls -l ./Phone/ESurfingDialer.zip

    - name: 上传ESurfingDialer的免Docke直接运行版本
      uses: actions/upload-artifact@v3
      with:
        name: ESurfingDialer的免Docke直接运行版本
        path: './Phone/ESurfingDialer.zip'

    - name: 获取天翼校园网官方Linux版本下载地址并下载，不能获取则使用预下载文件
      run: |
        cd ./PC/
        pip3 install requests beautifulsoup4 lxml
        python3 ./Get_ESurfingDialerClient.py

    - name: 检查天翼校园网官方Linux版本下载结果
      run: |
        ls -l ./PC

    - name: 生成更新日志
      run: echo "# 好的更新已经到来" > ${{ github.workspace }}-CHANGELOG.txt

    - name: 生成时间戳
      id: timestamp
      run: echo "TIMESTAMP=$(date +'%Y.%m.%d.%H.%M.%S')" >> $GITHUB_ENV

    - name: 创建Release
      uses: softprops/action-gh-release@v2
      with:
        body_path: ${{ github.workspace }}-CHANGELOG.txt
        tag_name: V${{ env.TIMESTAMP }}
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          ./ESurfingDialer/build/libs/* # ESurfingDialer的JAR构建产物
          ./Phone/ESurfingDockerPhone.tar.gz # ESurfingDockerPhone的Docker镜像
          ./Phone/ESurfingDialer.zip # ESurfingDialer的免Docke直接运行版本
